<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Creating the directory: {path}' => 'Creo la directory {path}',
    'Schema file generated for table {table} in {path}' => 'Schema del database generato per la tabella {table} in {path}',
    'Schemas for module {module} created' => 'Schemi del database per il modulo {module} creati',
    'Start creating migration schemas for module {module}' => 'Inizio a creare gli schemi di migrazione per il modulo {module}',
    'Table {table} does not exist in the database' => 'La tabella {table} non esiste nel database',
    'Changes for table {table} applied' => 'Cambiamenti per la tabella {table} applicati con successo',
    'Do you want to create the table?' => 'Vuoi creare la tabella',
    'Do you want to launch this command?' => 'Vuoi lanciare questo comando',
    'End tables migration for module {module}' => 'Fine della migrazione per il modulo {module}',
    'Execute the command: {command}' => 'Eseguo il comando {command}',
    'No changes for table {table}' => 'Nessun cambiamento per la tabella {table}',
    'Schema not found for table {table}' => 'Schema non trovato per la tabella {table}',
    'Start rollback procedure' => 'Inizio la procedura di rollback',
    'Start tables migration for module {module}' => 'Inizio la migrazione delle tabelle per il modulo {module}',
    'Table {table} create with command {createCommand}' => 'Tabella {table} creata con il comando {command}',
    'invalid schema file for table {table}' => 'Schema per la tabella {table} non valido',
];
